-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION public.recipe_like(recipe_row recipe, hasura_session json)
-- RETURNS boolean
-- LANGUAGE sql
-- STABLE
-- AS $$
-- SELECT EXISTS (
--     SELECT 1
--     FROM likes A
--     WHERE A.user_id = CAST((hasura_session ->> 'x-hasura-user-id') as INTEGER) AND A.recipe_id = recipe_row.id
-- );
-- $$;
